name: Build CV PDF

on:
  push:
  schedule:
    - cron:  '0 20 * * *' # run every day at 8:00pm

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Compile document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: martinmadsenCV.tex
          latexmk_use_xelatex: true

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: CV
          path: martinmadsenCV.pdf

